# Generated by Django 6.0 on 2026-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_summery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='post_type',
            field=models.CharField(choices=[('trending', 'Trending Now'), ('banner', 'Banner'), ('normal', 'Normal Post')], default='normal', max_length=10),
        ),
    ]
